# Generated by Django 5.0.3 on 2024-03-18 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loan',
            table='borrower_loan',
        ),
    ]
